apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: energy-balancing-mvp-argocd
  namespace: argocd
spec:
  project: default

  # No web-hook -> 3 minute scaping intervals
  source:
    repoURL: https://github.com/joachimbulow/energy-balancing-mvp-deployment
    targetRevision: HEAD
    path: /dev
  destination:
    server: https://kubernetes.default.svc
    namespace: energy-balancing-mvp

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: false
      prune: true
