apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: energy-balancing-mvp-argocd
  namespace: argocd
spec:
  project: default

  # Define a dependency on the umbrella-chart application
  dependencies:
    - name: umbrella-chart
      namespace: energy-balancing-mvp

  # Using app-of-apps pattern
  source:
    path: argocd/apps
    repoURL: https://github.com/joachimbulow/energy-balancing-mvp-deployment
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  # No web-hook -> 3 minute scaping intervals
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
