apiVersion: v2
name: umbrella-chart
type: application
version: 0.34.0
appVersion: "1.0.0"
dependencies:
  - name: strimzi-kafka-operator
    version: 0.34.0
    repository: https://strimzi.io/charts/
  - name: prometheus-kafka-exporter
    version: 2.1.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: influxdb
    version: 4.12.0
    repository: https://helm.influxdata.com/
