# Hopefully fixing annotation issue for ArgoCD when deploying crds having very long "last_config" values
global:
  crds:
    annotations:
      argocd.argoproj.io/sync-options: Replace=true

prometheus-kafka-exporter:
  kafkaServer:
    - mvp-cluster-kafka:9092
  prometheus:
    serviceMonitor:
      enabled: true
      namespace: energy-balancing-mvp
      additionalLabels:
        release: prom-stack

grafana:
  enabled: true

  persistence:
    enabled: true
    type: pvc
    storageClassName: default
    accessModes:
      - ReadWriteOnce
    size: 4Gi
    finalizers:
      - kubernetes.io/pvc-protection

influxdb:
  env:
    - name: INFLUXDB_DB
      value: "influx"
    - name: INFLUXDB_ADMIN_USER
      value: "admin"
    - name: INFLUXDB_ADMIN_PASSWORD
      value: "admin"

redis:
  auth:
    enabled: false

ingress-nginx:
  controller:
    replicaCount: 1

    service:
      type: LoadBalancer
      externalTrafficPolicy: Local

    config:
      use-forwarded-headers: "true"
      ssl-redirect: "false"

    ingressClassResource:
      enabled: true
      defaultClass: true

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
