strimzi-kafka-operator:
  replicas: 1
prometheus-kafka-exporter:
  kafkaServer:
    - mvp-cluster-kafka:9092
  prometheus:
    serviceMonitor:
      enabled: true
      namespace: energy-balancing-mvp
      additionalLabels:
        release: charts-v1
