strimzi-kafka-operator:
  replicas: 1
prometheus:
  server:
    global:
      ## How frequently to scrape targets
      scrape_interval: 30s
      ## How long until a scrape request times out
      scrape_timeout: 20s
      ## How frequently to evaluate rules
      evaluation_interval: 1m
