apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: umbrella-chart
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts
    repoURL: https://github.com/joachimbulow/energy-balancing-mvp-deployment
    targetRevision: HEAD
    helm:
      releaseName: charts-v1
      chart: charts
      valueFiles:
        - charts/values.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
