apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
spec:
  selector:
    # These were found using kubectl describe deployment
    app.kubernetes.io/instance: umbrella-chart
    app.kubernetes.io/name: grafana
    app.kubernetes.io/managed-by: Helm
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30001
  type: ClusterIP
