apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: energy-balancing-mvp
  labels:
    app: grafana
spec:
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - name: grafana-port
      port: 80
  type: LoadBalancer
