apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: energy-balancing-mvp
  labels:
    app: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
  type: LoadBalancer
