apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-no-crds
spec:
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 45.21.0
    helm:
      releaseName: prom-stack
      skipCrds: true
  destination:
    namespace: energy-balancing-mvp
    server: https://kubernetes.default.svc

  project: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
