apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-crds
spec:
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-45.21.0
    helm:
      releaseName: prom-stack
    directory:
      recurse: true
  destination:
    namespace: energy-balancing-mvp
    server: https://kubernetes.default.svc

  project: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true
