apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: umbrella-chart
spec:
  source:
    path: charts
    repoURL: https://github.com/joachimbulow/energy-balancing-mvp-deployment
    targetRevision: HEAD
    helm:
      releaseName: charts-v1
      valueFiles:
        - charts/values.yaml
  destination:
    namespace: energy-balancing-mvp
    server: https://kubernetes.default.svc

  project: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
