apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: util
spec:
  source:
    path: util
    repoURL: https://github.com/joachimbulow/energy-balancing-mvp-deployment
    targetRevision: HEAD
  destination:
    namespace: energy-balancing-mvp
    server: https://kubernetes.default.svc

  project: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: false

    syncOptions:
      - CreateNamespace=true
