# High availability Flink needs this to be able to create/delete pods etc
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-service-account
  namespace: energy-balancing-mvp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-role-binding
  namespace: energy-balancing-mvp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: flink-service-account
    namespace: energy-balancing-mvp
