apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: inertia-measurements
  labels:
    strimzi.io/cluster: mvp-cluster
    namespace: energy-balancing-mvp
spec:
  topicName: inertia_measurements
  # Two partitions, just for good measure
  partitions: 2
  replicas: 2
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: frequency-measurements
  labels:
    strimzi.io/cluster: mvp-cluster
    namespace: energy-balancing-mvp
spec:
  topicName: frequency_measurements
  # Two partitions, just for good measure
  partitions: 2
  replicas: 2
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: pem-requests
  labels:
    strimzi.io/cluster: mvp-cluster
    namespace: energy-balancing-mvp
spec:
  topicName: pem_requests
  # Two partitions, just for good measure
  partitions: 2
  replicas: 2
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: pem-responses
  labels:
    strimzi.io/cluster: mvp-cluster
    namespace: energy-balancing-mvp
spec:
  topicName: pem_responses
  # THIS IS KEY PARAMETER FOR SYSTEM LOAD OPTIMIZATION
  # We need at least as many partitions as there are N_BATTERIES in the battery simulations
  partitinos: 100
  # We MIGHT want to increase this number significantly due to the amount of traffic
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: battery-actions
  labels:
    strimzi.io/cluster: mvp-cluster
    namespace: energy-balancing-mvp
spec:
  topicName: battery_actions
  # Two partitions, just for good measure
  partitions: 2
  replicas: 2
