apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: mvp-cluster
  namespace: energy-balancing-mvp
spec:
  kafka:
    version: 3.4.0
    replicas: 10
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      # Use only the topics generated in kafka-topics.yaml
      auto.create.topics.enable: "false"
      # 1 week retention for logs
      log.retention.hours: 168
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.4"
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          # 300 Gi totally consumed by brokers
          size: 80Gi
          deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 4Gi
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
  entityOperator:
    topicOperator:
      watchedNamespace: energy-balancing-mvp
    userOperator: {}
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
