apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: inertia-measurements
  labels:
    strimzi.io/cluster: mvp-cluster
    namespace: energy-balancing-mvp
spec:
  topicName: inertia_measurements
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: frequency-measurements
  labels:
    strimzi.io/cluster: mvp-cluster
    namespace: energy-balancing-mvp
spec:
  topicName: frequency_measurements
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: pem-requests
  labels:
    strimzi.io/cluster: mvp-cluster
    namespace: energy-balancing-mvp
spec:
  topicName: pem_requests
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: pem-responses
  labels:
    strimzi.io/cluster: mvp-cluster
    namespace: energy-balancing-mvp
spec:
  topicName: pem_responses
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: battery-actions
  labels:
    strimzi.io/cluster: mvp-cluster
    namespace: energy-balancing-mvp
spec:
  topicName: battery_actions
