apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: battery
  namespace: energy-balancing-mvp
  labels:
    app: battery
spec:
  podManagementPolicy: Parallel
  replicas: 5
  selector:
    matchLabels:
      app: battery
  template:
    metadata:
      labels:
        app: battery
    spec:
      containers:
        - name: battery
          image: pemmvpregistry.azurecr.io/battery:v6
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "35m"
            limits:
              memory: "150Mi"
              cpu: "45m"
          env:
            - name: BROKER_URL
              value: "mvp-cluster-kafka.energy-balancing-mvp.svc.cluster.local:9092"
            - name: BROKER
              value: "KAFKA"
            - name: N_BATTERIES
              value: "5"
            - name: REQUEST_INTERVAL_SECONDS
              value: "300"
            - name: PACKET_POWER_W
              value: "4000" # Needs to correspond to TSO value
            - name: PACKET_TIME_S
              value: "30" # Needs to correspond to TSO value
            - name: UPPER_BOUND_BATTERY_CAPACITY
              value: "0.8"
            - name: LOWER_BOUND_BATTERY_CAPACITY
              value: "0.2"
            - name: CONSUMER_GROUP_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
