apiVersion: apps/v1
kind: Deployment
metadata:
  name: battery
  namespace: energy-balancing-mvp
  labels:
    app: battery
spec:
  replicas: 5
  selector:
    matchLabels:
      app: battery
  template:
    metadata:
      labels:
        app: battery
    spec:
      containers:
        - name: battery
          image: pemmvpregistry.azurecr.io/battery:v5
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "250Mi"
              cpu: "70m"
          env:
            - name: BROKER_URL
              value: "mvp-cluster-kafka.energy-balancing-mvp.svc.cluster.local:9092"
            - name: BROKER
              value: "KAFKA"
            - name: N_BATTERIES
              value: "5"
            - name: REQUEST_INTERVAL_SECONDS
              value: "300"
            - name: PACKET_POWER_W
              value: "4000"
            - name: PACKET_TIME_S
              value: "30"
            - name: UPPER_BOUND_BATTERY_CAPACITY
              value: "0.8"
            - name: LOWER_BOUND_BATTERY_CAPACITY
              value: "0.2"
